default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  utc: true

development:
  <<: *default
  database: course_work_development

test:
  <<: *default
  database: course_work_test

production:
  <<: *default
  database: course_work_production
  username: course_work
